POST http://localhost:3003/api/blogs 
Content-Type: application/json
Authorization: bearer TOKENHERE

{
      "author": "Ada lovelace",
      "title": "Green leaves rock",
      "url": "www.allaboutgreenlife.com",
      "likes": 35
}
###

GET http://localhost:3003/api/blogs